version: "3.8"
services:
  local_file_bazaar:
    image: mysql:8.0.34
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: blog_db
      MYSQL_USER: blogger
      MYSQL_PASSWORD: travel
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: local_file_bazaar
    depends_on:
      - local_file_bazaar
    ports:
      - "8080:80"