version: "3.8"
services:
  in311_local_file_bazaar_mysql:
    image: mysql:latest
    container_name: in311_local_file_bazaar_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: blog_db
      MYSQL_USER: blogger
      MYSQL_PASSWORD: travel
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: in311_local_file_bazaar_phpmyadmin
    depends_on:
      - in311_local_file_bazaar_mysql
    ports:
      - "8080:80"